### ISSUE TITLE
Welcome wagon for the meeting

### ISSUE THREAD

**Issue by tracykteal** [carpentries/carpentrycon#1]
Welcoming people for a meeting helps set the tone and how people engage with the meeting. 

The Write the Docs community put together a Welcome Wagon document that they found to be very helpful and effective for inclusivity
 
http://www.writethedocs.org/conf/na/2017/welcome-wagon/
 
Tweet: https://twitter.com/ericholscher/status/875786858042609664
 
A document like could be something good for CarpentryCon.

**Comment by fpsom** [comment]
Thanks @tracykteal  ! Closing issue now after CarpentryCon 2018.
