### ISSUE TITLE
CarpentryCon debriefing

### ISSUE THREAD

**Issue by tracykteal** [carpentries/carpentrycon#119]
For debriefing information after CarpentryCon, we've put together a Google doc to capture what we did, what worked and what could be improved. 

It's organized in sections of the different categories of what was done. This document will be a basis for a CarpentryCon cookbook and also help future organizing committees. After capturing ideas, we can also turn things to into github issues to follow up on as needed.

Google doc: https://docs.google.com/document/d/1sm1saUP6gtSkBrhTBE_8LKmK_PMaEmp_UUkx9WOW4oA/edit#

Please add thoughts for debriefing, particularly for the different areas that you worked on!

**Comment by malvikasharan** [comment]
The TaskForce members have added their points in the document. Thank you so much for getting it started. Closing this issue.
