### ISSUE TITLE
Move Minutes folder to CarpentryCon2018 folder

### ISSUE THREAD

**Issue by sstevens2** [carpentries/carpentrycon#129]
The 'minutes' folder only includes minutes from carpentrycon2018 so I think we should move it into the carpentrycon2018 folder.  Otherwise people looking for cc2020 minutes will find them first since they are in main and the cc2020 minutes are in the cc2020 folder.

**Comment by malvikasharan** [comment]
Thanks Sarah. I moved the files now. I will close this issue.
