### ISSUE TITLE
Check who controls the domain name (DN) for carpentrycon.org

### ISSUE THREAD

**Issue by anenadic** [carpentries/carpentrycon#139]
@BinxiePeterson  Take ownership of the domain name (DN) for carpentrycon.org, contact Belinda Weaver to check if she owns it

**Comment by BinxiePeterson** [comment]
Email has been sent and website-and-outreach team CC'd. Will update as soon as I get feedback.

**Comment by fmichonneau** [comment]
The Carpentries owns the domain. We want to keep control of the domains that are related to us. Let me know what you need. Personally, I'd like it if we used subdomains (e.g., cc2020.carpentrycon.org) for each event and the top domain as a landing page that links to the different editions.

**Comment by BinxiePeterson** [comment]
@fmichonneau I like your suggestion of subdomains. I have not ever worked with this before , I am learning a lot. This may be a very basic question, but how do you create a subdomain?

**Comment by anenadic** [comment]
I agree @fmichonneau with the use of subdomains, as we already have to maintain the list of past CarpentryCons. Also about the ownership of the domain - absolutely the Carpentries should have ownership of it (we thought it was done in Belinda's name and had issues in the past wrt whose email address it has been registered under). So we'd need a new landing page for carpentrycon.org and then links to new subdomains cc2018.carpentrycon.org and cc2020.carpentrycon.org. Who is the best person to task with the @fmichonneau?

**Comment by fmichonneau** [comment]
Can you please make me an admin for the carpentrycon GitHub organization so I can set things up? Thanks!

**Comment by anenadic** [comment]
Let's see if @malvikasharan or @BinxiePeterson can help with this (making @fmichonneau the owner of carpentrycon repo) - I am not the owner myself, just a contributor.

**Comment by BinxiePeterson** [comment]
@anenadic @fmichonneau I have no idea how this works, but found these instructions just by doing a quick search: https://help.github.com/en/articles/changing-a-persons-role-to-owner Just checked and saw that I am also only a contributor. Then I went to the carpentrycon user and saw 5 people listed:
![image](https://user-images.githubusercontent.com/17334907/57675662-df5eac00-7622-11e9-8a3a-402ff3bceb0f.png) @fmichonneau it seems like you should be able to make yourself an owner then? I wasn't able to. Could you please give it a try and let us know? The next step would be to ask @jduckles for help.

**Comment by fmichonneau** [comment]
the content of the CarpentryCon websites is currently hosted in a different GitHub organization (https://github.com/carpentrycon) for which I don't have owner-level access. No one there is listed publicly so it's not clear who the owners are.

**Comment by BinxiePeterson** [comment]
Oh yes, sorry, it is a different repository. I do not know how to fix this. Hopefully @malvikasharan can help.

**Comment by jduckles** [comment]
Looks like the owners of github.com/carpentrycon are: @serahrono and @tracykteal 
![image](https://user-images.githubusercontent.com/119403/57730100-da196400-76eb-11e9-9bf1-58866b928352.png)

**Comment by tracykteal** [comment]
@fmichonneau I invited you to the organization as an Owner.

**Comment by fmichonneau** [comment]
<https://cc2018.carpentrycon.org> and <https://cc2020.carpentrycon.org> are now up. 

www.carpentrycon.org still points to the 2018 website at this stage. If someone can set up a repo for a landing page that would describe what CarpentryCon is and links to the 2018 and 2020 events, let me know I'll point https://carpentrycon.org and https://www.carpentrycon.org to that landing page.

**Comment by anenadic** [comment]
I suggest we put the CarpentryCon landing page in the existing repo: https://github.com/carpentries/carpentries.org (already pointed to by https://www.carpentrycon.org) as the CarpentryCon 2018 website has been copied to https://carpentrycon.github.io/carpentrycon2018. Then https://cc2018.carpentrycon.org will point to https://carpentrycon.github.io/carpentrycon2018/ and https://cc2020.carpentrycon.org will point to https://carpentrycon.github.io/carpentrycon2020/. Gosh! I can do a simple landing page as a quick solution but that means removing everything in the https://github.com/carpentries/carpentries.org repo and I'd like someone to approve this @tracykteal? Even though things are reversible. Also note that we have agreed to have a production ready CarpentryCon2020 website by the beginning of June (though it is in a very good shape as is) - so we can plan the DN switch.

**Comment by fmichonneau** [comment]
https://github.com/carpentries/carpentries.org is the main carpentries website, I don't think we want to delete anything from there :sweat_smile: 

I suggest creating a landing page in a new repository within the [carpentrycon github organization](https://github.com/carpentrycon) and calling it `carpentrycon.org`.

**Comment by anenadic** [comment]
Duh, you are right @fmichonneau. What you suggest was my original idea but then I started looking into the repos and thought I had a better idea. Clearly not. I'll do that then.

**Comment by anenadic** [comment]
@fmichonneau I have set up the new carpentries.org at https://github.com/carpentrycon/carpentrycon.org with a basic landing page visible at: https://carpentrycon.github.io/carpentrycon.org/. Any comments welcome so after review we can do the switch.

**Comment by anenadic** [comment]
We are ready for the DN switch @fmichonneau. People at the CaroentryCon organising committee asked if we could have the following subdomains: https://2018.carpentrycon.org and https://2020.carpentrycon.org instead of https://cc2018.carpentrycon.org and https://cc2020.carpentrycon.org.
