### ISSUE TITLE
Overarching theme?

### ISSUE THREAD

**Issue by fpsom** [carpentries/carpentrycon#2]
* _CarpentryCon: Building Capacity_
 
* _CarpentryCon: Moving Globally, Building Locally_

* _CarpentryCon: Building Locally, Connecting Globally_

**Comment by laufers** [comment]
I like the second one. As the carpentries move into new areas around the globe, the workshop is still a local event and is helping to build local capabilities and community.

**Comment by mkuzak** [comment]
this would also include how to setup local study group / hacky hour

**Comment by jduckles** [comment]
I'd go local -> global rather than global -> local. Most people relate to their local challenges more readily.

**Comment by tracykteal** [comment]
From @jduckles comment, another suggestion "Building Locally, Connecting Globally"

**Comment by weaverbel** [comment]
These decided now so closing this.
