### ISSUE TITLE
Ideas for side sessions / BoFs

### ISSUE THREAD

**Issue by fpsom** [carpentries/carpentrycon#3]
1. improv
2. teaching practices
3. how to efficiently hold meetings
4. Technical topics (such as JupyterHub)
5. lightning talks
6. extra session slow with the opportunity to pitch your content for this session at the lightning talks
7. BYOL - Bring Your Own Lesson: Bring a lesson you're working on and turn it into a Carpentry style lesson
8. How to create a lesson
9. How to organize a small conference

**Comment by mkuzak** [comment]
point 5 is actually two things (separate points):
* lightning talks
* extra session slow with the opportunity to pitch your content for this session at the lightning talks

**Comment by fpsom** [comment]
Thanks @mkuzak. I've just updated the original post.

**Comment by fpsom** [comment]
I'm closing this issue, as I've posted each idea as an individual topic.
