### ISSUE TITLE
BoF on how to efficiently hold meetings

### ISSUE THREAD

**Issue by fpsom** [carpentries/carpentrycon#8]

**Comment by k8hertweck** [comment]
This is a great topic, with lots of room for helping our community operate better. More specifically:

- running small group meeting
- facilitating virtual discussions (tips and tricks for participation)
- enabling equal participation in meeting attendees

**Comment by fpsom** [comment]
Thanks @k8hertweck  ! Closing issue now after CarpentryCon 2018.
